# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/controlplane.cluster.x-k8s.io_agentcontrolplanes.yaml
#+kubebuilder:scaffold:crdkustomizeresource

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    cluster.x-k8s.io/v1beta1: v1alpha1
