# permissions for end users to view openshiftassistedcontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openshiftassistedcontrolplane-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cluster-api-agent
    app.kubernetes.io/part-of: cluster-api-agent
    app.kubernetes.io/managed-by: kustomize
  name: openshiftassistedcontrolplane-viewer-role
rules:
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - openshiftassistedcontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - controlplane.cluster.x-k8s.io
  resources:
  - openshiftassistedcontrolplanes/status
  verbs:
  - get
