apiVersion: v1
data:
  .dockerconfigjson: <PULLSECRET>
kind: Secret
metadata:
  name: pull-secret
  namespace: test-capi
type: kubernetes.io/dockerconfigjson
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test-multinode
  namespace: test-capi
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 172.18.0.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha2
    kind: OpenshiftAssistedControlPlane
    name: test-multinode
    namespace: test-capi
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3Cluster
    name: test-multinode
    namespace: test-capi
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: test-multinode
  namespace: test-capi
spec:
  controlPlaneEndpoint:
    host: test-multinode.lab.home
    port: 6443
  noCloudProvider: true
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha2
kind: OpenshiftAssistedControlPlane
metadata:
  name: test-multinode
  namespace: test-capi
  annotations: {}
    #cluster.x-k8s.io/release-image-repository-override: registry.ci.openshift.org/ocp/release
spec:
  openshiftAssistedConfigSpec:
    pullSecretRef:
      name: "pull-secret"
    sshAuthorizedKey: <SSH_AUTHORIZED_KEY>
    nodeRegistration:
      kubeletExtraLabels:
      - 'metal3.io/uuid="${METADATA_UUID}"'
  distributionVersion: 4.19.0-ec.2-x86_64
  config:
    apiVIPs:
    - 192.168.222.40
    ingressVIPs:
    - 192.168.222.41
    baseDomain: lab.home
    pullSecretRef:
      name: "pull-secret"
    sshAuthorizedKey: <SSH_AUTHORIZED_KEY>
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: Metal3MachineTemplate
      name: test-multinode-controlplane
      namespace: test-capi
  replicas: 3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-multinode-controlplane
  namespace: test-capi
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: disabled
      dataTemplate:
        name: test-multinode-controlplane-template
      image:
        checksum: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/pre-release/dev-4.19/sha256sum.txt
        checksumType: sha256
        format: qcow2
        url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/pre-release/dev-4.19/rhcos-dev-4.19-x86_64-nutanix.x86_64.qcow2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-multinode-workers-2
  namespace: test-capi
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: metadata
      dataTemplate:
        name: test-multinode-workers-template
      image:
        checksum: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/pre-release/dev-4.19/sha256sum.txt
        checksumType: sha256
        format: qcow2
        url: https://mirror.openshift.com/pub/openshift-v4/x86_64/dependencies/rhcos/pre-release/dev-4.19/rhcos-dev-4.19-x86_64-nutanix.x86_64.qcow2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: test-multinode-controlplane-template
  namespace: test-capi
spec:
  clusterName: test-multinode
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: test-multinode-workers-template
  namespace: test-capi
spec:
  clusterName: test-multinode
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: test-multinode-worker
  namespace: test-capi
  labels:
    cluster.x-k8s.io/cluster-name: test-multinode
spec:
  clusterName: test-multinode
  replicas: 2
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: test-multinode
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: test-multinode
    spec:
      clusterName: test-multinode
      bootstrap:
        configRef:
          name: test-multinode-worker
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
          kind: OpenshiftAssistedConfigTemplate
      infrastructureRef:
        name: test-multinode-workers-2
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: Metal3MachineTemplate
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
kind: OpenshiftAssistedConfigTemplate
metadata:
  name: test-multinode-worker
  namespace: test-capi
  labels:
    cluster.x-k8s.io/cluster-name: test-multinode
spec:
  template:
    spec:
      nodeRegistration:
        # name: '${METADATA_NAME}'
        kubeletExtraLabels:
          - 'metal3.io/uuid="${METADATA_UUID}"'
      pullSecretRef:
        name: "pull-secret"
      sshAuthorizedKey: <SSH_AUTHORIZED_KEY>
