apiVersion: v1
data:
  .dockerconfigjson: <PULLSECRET>
kind: Secret
metadata:
  name: pull-secret
  namespace: test-capi
type: kubernetes.io/dockerconfigjson
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test-multinode
  namespace: test-capi
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 172.18.0.0/20
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: OpenshiftAssistedControlPlane
    name: test-multinode
    namespace: test-capi
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3Cluster
    name: test-multinode
    namespace: test-capi
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: test-multinode
  namespace: test-capi
spec:
  controlPlaneEndpoint:
    host: test-multinode.lab.home
    port: 6443
  noCloudProvider: true
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: OpenshiftAssistedControlPlane
metadata:
  name: test-multinode
  namespace: test-capi
spec:
  openshiftAssistedConfigSpec:
    pullSecretRef:
      name: "pull-secret"
    sshAuthorizedKey: <SSH_AUTHORIZED_KEY>
  config:
    apiVIPs:
    - 192.168.222.40
    ingressVIPs:
    - 192.168.222.41
    releaseImage: quay.io/openshift-release-dev/ocp-release:4.17.0-rc.2-x86_64 #registry.ci.openshift.org/ocp/release:4.17.0-0.nightly-2024-08-06-034102 #quay.io/openshift-release-dev/ocp-release:4.17.0-ec.2-x86_64
    baseDomain: lab.home
    pullSecretRef:
      name: "pull-secret"
    sshAuthorizedKey: <SSH_AUTHORIZED_KEY>
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: Metal3MachineTemplate
      name: test-multinode-controlplane
      namespace: test-capi
  replicas: 3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-multinode-controlplane
  namespace: test-capi
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: disabled
      dataTemplate:
        name: test-multinode-controlplane-template
      image:
        checksum: null
        checksumType: null
        format: live-iso
        url: https://abcde
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: test-multinode-workers-2
  namespace: test-capi
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: metadata
      dataTemplate:
        name: test-multinode-workers-template
      image:
        checksum: null
        checksumType: null
        format: live-iso
        url: https://abcde
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: test-multinode-controlplane-template
  namespace: test-capi
spec:
  clusterName: test-multinode
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: test-multinode-workers-template
  namespace: test-capi
spec:
  clusterName: test-multinode
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: test-multinode-worker
  labels:
    cluster.x-k8s.io/cluster-name: test-multinode
spec:
  clusterName: test-multinode
  replicas: 2
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: test-multinode
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: test-multinode
    spec:
      clusterName: test-multinode
      version: "1.30.0"
      bootstrap:
        configRef:
          name: test-multinode-worker
          apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
          kind: OpenshiftAssistedConfigTemplate
      infrastructureRef:
        name: test-multinode-workers-2
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
        kind: Metal3MachineTemplate
---
apiVersion: bootstrap.cluster.x-k8s.io/v1alpha1
kind: OpenshiftAssistedConfigTemplate
metadata:
  name: test-multinode-worker
  labels:
    cluster.x-k8s.io/cluster-name: test-multinode
spec:
  template:
    spec:
      pullSecretRef:
        name: "pull-secret"
      sshAuthorizedKey: <SSH_AUTHORIZED_KEY>


      # quay.io/eranco74/ocp:4.16.0-0.ci.test-2024-06-18-154755-ci-ln-mkd6npb-latest-x86_64
      # bug ASSISTED INSTALLER STUCK with old images (registry03...)